encoding                        : utf-8
# Dependencies
# markdown                        : redcarpet
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - redcarpet
  - rouge
  - jekyll-paginate-v2

source: src

highlighter                     : rouge
redcarpet                       :
  extensions                    : ["with_toc_data"]

# Permalinks
permalink                       : /:categories/:title/

# Setup
title                           : Mildronize's blog
tagline                         : mildronize-blog
description                     : My notes and interesting things
keywords                        : [note, computer, programming, script, knowledge, coding, technique, collection, glossary, data, infomation, internet, web]
url                             : https://www.pagunmarun.com
# for dev
image_url                       : /public/images

# Development
# static_url                     : /public/static.pagunmarun.com

# Productoin
static_url                      : https://static.pagunmarun.com

# static_url                      : https://pagunmarun.github.io   (old site)

shirts_prefix_url       : /images/shirts/
shirts:
  - "showcase1.jpg"
  - "showcase2.jpg"
  - "showcase3.jpg"
  - "showcase4.jpg"
  - "showcase6.jpg"
  - "showcase7.jpg"
  - "showcase8.jpg"
  - "showcase9.jpg"
  - "showcase10.jpg"
  - "showcase11.jpg"
  - "showcase12.jpg"
  - "showcase13.jpg"
  - "showcase14.jpg"
  - "showcase15.jpg"
  - "showcase16.jpg"

sponspors_prefix_url       : /images/sponsors/
bigger_sponsers:
# Type 5
  # - "scb.jpg"
# Type 6
  - "icc-hatyai.jpg"
  - "archemica.jpg"
  - "electric.jpg"
# Type 7
  - "corp-sci-tech.png"
  - "ward-medic.png"
  - "ksp.jpg"
  - "nanaphun.jpg"


sponspors:

  - "Logo_Alumni_association.jpg"
  - "grad-psu.png"
  - "psu-sci.png"
  - "logo-sercoop.jpg"
  - "CIS_PSU_TH-H.jpg"
  - "PSU_Logo_Faculty-of-Natural_Resources_TH.jpg"


author                          : 
  codename                      : mildronize
  name                          : Thada Wangthammang
  email                         : mildronize@gmail.com
  profile                       : images/my-profile.jpg
  facebook                      : mildronize
  twitter                       : mildronize
  google_plus                   : mildronize

google_analytics_id             : UA-62565035-3

# Fix a problem following https : //github.com/jekyll/jekyll/issues/3525
exclude                         : [vendor, node_modules]

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed


# SEO
twitter:
  username: mildronize
  card: summary

logo                            : /public/favicon.jpg

social:
  name: Thada Wangthammang
  links:
    - https://twitter.com/mildronize
    - https://www.facebook.com/mildronize
    - https://www.linkedin.com/in/thada-wangthammang-281894a6
    - https://plus.google.com/u/0/+MildronizeWangth
    - https://github.com/mildronize


# Html compress
# https://github.com/penibelst/jekyll-compress-html
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [head, body]

# Plugin Config: 
# Jekyll/paginate
# paginate                        : 10
# paginate_path                   : "/page/:num/"

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  # title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  # category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  # indexpage: 'index'

############################################################
